### PR TITLE
Fix issue with play again functionality, already playing functionality + UI tweak

### PR DESCRIPTION
**Pull request by darrentaytay**
server.js was still referencing `socket.gameRoom` which no longer exists after the game refactoring by @hkan. This was causing the play again functionality not to work and also the functionality which informs users if an invited user is currently in a game.

Also added "autofocus" property to the "Enter your username" text field - was bugging me having to click/tab into it when testing!

### CODE REVIEW

**Comment by andreaselia** [comment]
Awaiting issue with turn switching to be fixed.

**Comment by darrentaytay** [comment]
@AndreasElia those issues should be sorted now. Please check and let me know 👍

**Comment by darrentaytay** [comment]
@hkan - @AndreasElia is still having issues with my code but it works fine for me - so we might need a third pair of eyes to confirm if it's working or not.

Basically, the "Play Again" functionality wasn't working.

My first attempt at fixing it, fixed the "play again" functionality, however, on the 2nd game, the markers weren't showing. I fixed this and it works for me locally, however, @AndreasElia can't get it to work on his machine.

**Comment by hkan** [comment]
I'll try to take a look tonight. Thanks for the heads up! 👍

**Pull request merged**
